name: 'Terraform Apply with OIDC Authentication'

on:
  push:
    branches:
      - testing 
  pull_request:
    branches:
      - testing

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'  # Specify the Terraform version you want to use

      - name: Configure AWS OIDC Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::245843320375:role/githubaiuth
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActionsSession
          # OIDC authentication is automatically handled by the AWS Action

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
