name: 'Terraform Apply with OIDC Authentication'

on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing

permissions:
  id-token: write  


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git safe directory
        run: |
          git config --global --add safe.directory /home/runner/work/document-workflow/
          
          
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: 'ShubhamChauhan15/document-workflow'
          token: ${{ secrets.GITHUB_TOKEN }}  


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'  

      - name: Configure AWS OIDC Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::245843320375:role/githubaiuth  
          aws-region: ${{ secrets.AWS_REGION }}  
          role-session-name: GitHubActionsSession 
          

      - name: Terraform Init
        run: terraform init  # Initialize Terraform

      - name: Terraform Plan
        run: terraform plan  # Run Terraform Plan

      - name: Terraform Apply
        run: terraform apply -auto-approve  

      - name: Terraform Destroy
        run: terraform destroy  --auto-approve

